name: Version and Changelog

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  version-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Determine current version
        id: current_version
        run: |
          current_version=$(node -p "require('./package.json').version")
          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT

      - name: Generate version and changelog
        run: |
          if [ -z "${{ steps.current_version.outputs.current_version }}" ]; then
            echo "No version found in package.json, initializing to 0.1.0"
            npm version 0.1.0 --no-git-tag-version
          fi
          npm run release

      - name: Push changes
        run: |
          git push --follow-tags origin main