name: Version and Changelog

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  version-and-changelog:
    runs-on: ubuntu-latest
    # Add permissions block to ensure the action can create commits and tags
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Add token authentication
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine current version
        id: current_version
        run: |
          current_version=$(node -p "require('./package.json').version || '0.1.0'")
          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT

      - name: Generate version and changelog
        run: |
          if [ -z "${{ steps.current_version.outputs.current_version }}" ]; then
            echo "No version found in package.json, initializing to 0.1.0"
            npm version 0.1.0 --no-git-tag-version
          fi
          npm run release

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --follow-tags origin main